### ISSUE TITLE
Problems encountered in discover device.

### ISSUE THREAD

**Issue by WwtGitHub** [infiniteautomation/BACnet4J#15]
Receive equipment reports I - AM messages, perform IAmRequest handle method of the execution to 117 row DiscoveryUtils. The getExtendedDeviceInformation (localDevice, rd）, timeout exception occurs, the timeout after retry mechanism for sending messages by default, after the success will not perform 118 lines of localDevice.getEventHandler().fireIAmReceived(rd). The code will not execute the iAmReceived method in the device listener, then retry can not solve the problem? Thanks.

**Comment by mlohbihler** [comment]
You appear to be using an old version of the software. The current supported version is 4.1.4.

**Comment by WwtGitHub** [comment]
Thank you.
