### ISSUE TITLE
Wrong loop condition in LocalDevice?

### ISSUE THREAD

**Issue by JinchunWei** [infiniteautomation/BACnet4J#17]
In the initialization of LocalDevice, when it tries to find an available id, should the loop condition at 323 be remaining instead of attempts? 
From my understanding the loop is supposed to be terminated after 10 times of failure to obtain a device id, however, current implementation may not stop after 10 attempts but tries for ever until it finds an id. Meanwhile,  an Exception will be thrown if available id is found at the **11th** attempt, which is another reason for which I think the loop condition should be remaining--.

**Comment by mlohbihler** [comment]
Yes, you are correct. The condition should be checking the value of remaining instead of attempts. I've pushed a fix.
