### ISSUE TITLE
No TLS on Mango's Maven repo?

### ISSUE THREAD

**Issue by Frozenlock** [infiniteautomation/BACnet4J#20]
Error message from my building tool when trying to download BACnet4J : 

```
Tried to use insecure HTTP repository without TLS.
```

**Comment by terrypacker** [comment]
Our repo is HTTPS, did you perhaps configure your tool to point at an HTTP URL?  I've only used Maven with our Repository so I can't comment on the configuration of other tools but if you let us know what tool we can take a look?

**Comment by terrypacker** [comment]
Thanks.  I'll get that fix in shortly.
