### ISSUE TITLE
v3 to v4/v5 : Non-IP devices no longer discovered?

### ISSUE THREAD

**Issue by Frozenlock** [infiniteautomation/BACnet4J#23]
My network has one BACnet/IP device able to bridge to the rest of the MS/TP network.

In v3 I was able to see and communicate with every devices (IP and MS/TP) via BACnet/IP.

Since V4 the only devices I can see/communicate with are the BACnet/IP ones.
Is there a new configuration or listener I need to use to be able to communicate with the MS/TP devices?

**Comment by JCP17** [comment]
I have the same problem but at migration from V2 to 3.2.2.
Is there any information on this yet?

**Comment by Frozenlock** [comment]
No. I've narrowed down the problem to the handle (https://github.com/infiniteautomation/BACnet4J/blob/master/src/main/java/com/serotonin/bacnet4j/service/unconfirmed/IAmRequest.java#L84).

It appears that if something goes wrong there, the remote device isn't added to the list and the `fireIAmReceived` is never fired.

**Comment by Frozenlock** [comment]
[V5 : I confirm that the problem is coming from `DiscoveryUtils.getExtendedDeviceInformation`. When it fails, the extended information is never fetched again and the `IAmReceived` event is never fired.

I fixed it in a fork by removing the call to `DiscoveryUtils.getExtendedDeviceInformation` from the `IAmRequest` handling and adding a similar function to a `IAmReceived` listener. This way the extended info retrieval is entirely configurable and doesn't screw up the event when encountering an error.

**Comment by terrypacker** [comment]
Any chance you can make a PR for that fix from your Fork?

Thanks!

**Comment by lovefamilyC** [comment]
Brother, according to this method can indeed get the remote device object, but always return to the object property when reporting BACnetTimeoutException
