### ISSUE TITLE
unable to get class bacnet4j.npdu.ip.IpNetworkBuilder from maven provided in the pom.xml

### ISSUE THREAD

**Issue by meitf** [infiniteautomation/BACnet4J#33]
I use the pom.xml to get bacnet  unable to getbacnet4j-5.0.0-SNAPSHOT.jar
but the class bacnet4j.npdu.ip.IpNetworkBuilder is not in the jar, why ?

**Comment by terrypacker** [comment]
The bacnet4j-5.5.0-SNAPSHOT had not been built and uploaded to the maven repository.  I have done this now so you should be able to get the jar.  Note this version of the library is in development and not fully tested.
