### ISSUE TITLE
5.0.0 release plan

### ISSUE THREAD

**Issue by nicola-lunghi** [infiniteautomation/BACnet4J#37]
Hi
do you have any plan to do a release soon?

**Comment by kevinherron** [comment]
The README suggests 5.0.0 and 5.0.1 have been released but I do not see these in Nexus - is this still in progress?

**Comment by terrypacker** [comment]
Sorry, I had edited the readme so I didn't forget to include that change when we do go about releasing 5.0.1.  I guess it's been long enough that no more changes will get in so I'll do that release next week.
