### ISSUE TITLE
Repository proxy error

### ISSUE THREAD

**Issue by odwrotnie** [infiniteautomation/BACnet4J#47]
The repos:

- https://maven.mangoautomation.net/repository/ias-snapshot/
- https://maven.mangoautomation.net/repository/ias-release/

throws `proxy error`.

```
Proxy Error
The proxy server could not handle the request GET /repository/ias-snapshot/.
Reason: Error during SSL Handshake with remote server
```

**Comment by splatch** [comment]
As a workaround you can temporary try to use https://mvnrepository.com/artifact/org.code-house.bacnet4j/api/1.1.0 - it brings earlier snapshot of bacnet4j 5.0 via maven central.
Package names remain the same as it is just a wrapper/repackaging of lib.
