### ISSUE TITLE
Non-SNAPSHOT release needed for 5.0.2

### ISSUE THREAD

**Issue by WhittlesJr** [infiniteautomation/BACnet4J#48]
```
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: 
Could not transfer artifact com.serotonin:bacnet4j:pom:5.0.2 from/to ias-snapshots (https://maven.mangoautomation.net/repository/ias-snapshot/): 
Repository version policy: SNAPSHOT does not allow version: 5.0.2 (400)
```

**Comment by terrypacker** [comment]
@WhittlesJr it looks like you are trying to use the ias-snapshots repo to get a release.  Use the ias-releases repo:

**Comment by WhittlesJr** [comment]
I have both ias-releases and ias-snapshots configured. If I take away ias-snapshots, it fails to resolve 5.0.2:

`
Error building classpath. Could not find artifact com.serotonin:bacnet4j:jar:5.0.2 in central (https://repo1.maven.org/maven2/)
`

**Comment by terrypacker** [comment]
Ah I see.  In 5.0 the maven coordinates changed:
```
	<groupId>com.infiniteautomation</groupId>
	<artifactId>bacnet4j</artifactId>
```

**Comment by WhittlesJr** [comment]
Oh ok. Thank you!
